import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en" className="h-screen">
      <body
        className={`${inter.className}
        flex justify-center items-center align-middle bg-cover bg-center bg-no-repeat h-[100dvh]`}
        style={{ backgroundImage: `url('/images/png/main-background.png')` }}
      >
        <div className="w-full h-full bg-primary desktop:max-w-5xl desktop:rounded-md desktop:h-[80%] desktop:overflow-auto ">
          {children}
        </div>
      </body>
    </html>
  )
}
